### PR TITLE
Add RPCAddr option for the JSON-RPC API

### PR DESCRIPTION
**Pull request by nfeignon**
Allows choosing the JSON-RPC API listening interface.
Set it to localhost as default for security considerations.
It currently listens on any interface (0.0.0.0).

### CODE REVIEW

**Comment by albrow** [comment]
Thanks @nfeignon! Sorry for the late reply, we were busy at Ethereum Devcon last week.

This is a good change, but if we're going to allow users to specify a custom listen address, I would rather combine `RPC_ADDR` and `RPC_PORT` into a single environment variable for convenience. Can we change the `RPC_ADDR` env var to expect an IP address as well as a port? Then we can deprecate `RPC_PORT` and eventually remove it.

**Comment by fabioberger** [comment]
@nfeignon we unfortunately had to force-push to `development` under exceptional circumstances. Could you please rebase your PR off of development?

The steps assuming you've updated your forks `development` to be identical to upstream would be:

```
git checkout feature/add-rpc-addr-option
git checkout -b feature/add-rpc-addr-option-old
git checkout development
git branch -D feature/add-rpc-addr-option
git checkout -b feature/add-rpc-addr-option
git cherry-pick c11591e14238808a7cfd34ce849375546b45c0b1
git push origin feature/add-rpc-addr-option -f
```

**Comment by nfeignon** [comment]
@fabioberger No problem, I've rebased my PR.

@albrow I chose to separate RPC_ADDR and RPC_PORT because that's what Parity (--jsonrpc-port, --jsonrpc-interface) and Geth (--rpcaddr, --rpcport) do but I don't mind editing my PR :)
Should I remove RPC_PORT completely or ignore it if RPC_ADDR is defined? What about the default interface (any or localhost) if only RPC_PORT is defined?

**Comment by albrow** [comment]
> Should I remove RPC_PORT completely or ignore it if RPC_ADDR is defined? What about the default interface (any or localhost) if only RPC_PORT is defined?

Here's what I'm thinking:

- Let's `RPC_PORT` for now, in order to maintain backwards compatibility.
- If `RPC_ADDR` is defined, we should ignore `RPC_PORT`.
- `RPC_ADDR` should be expected to always include the address *and* port.
- If `RPC_PORT` is defined and `RPC_ADDR` is not defined, we should use the current default bind address: `0.0.0.0` to maintain backwards compatibility.

Then, in a future release, we can remove the `RPC_PORT` environment variable.

**Comment by albrow** [comment]
@nfeignon talked it over with @fabioberger and since we are nearing the `6.0.0` release at this point, we would like to go ahead and break backwards compatibility here. (It's better to do it now than later since we are still in beta at the moment).

Instead of what I suggested in my previous comment, let's simply remove `RPC_PORT`. `RPC_ADDR` should be expected to always include the address and port.

**Comment by nfeignon** [comment]
> Instead of what I suggested in my previous comment, let's simply remove `RPC_PORT`. `RPC_ADDR` should be expected to always include the address and port.

Great, I updated my commit to remove RPC_PORT.

**Comment by albrow** [comment]
@nfeignon in the interest of time, I'm moving this over to https://github.com/0xProject/0x-mesh/pull/487 so I can fix the merge conflicts for you. You will still get credited for your commit on GitHub.

Thanks again for your contribution and thank you for bearing with us!

**Pull request closed without merging**
