### PR TITLE
Return error on invalid network ID

### PR DESCRIPTION
**Pull request by linki**
This is a proposal for implementing the network ID check mentioned in #60.

### CODE REVIEW

**Comment by fabioberger** [comment]
Thanks a lot for the PR @linki! Really appreciate the help. 

If you grep the codebase for `constants.NetworkIDToContractAddresses` you will see that we do this same lookup in many different places throughout the codebase. Would you be willing to replace all these lookups with the helper method you wrote? 

@albrow where do you think the `getContractAddressesForNetworkID` method should live? So far we are going to be using it in `main.go`, `ethwatch`, `meshdb`, `ws` and`zeroex` packages.

**Comment by albrow** [comment]
Thanks @linki!

@fabioberger how about in the `ethereum` package? I would also be open to creating a new package (e.g. `addrutils`) but only if there's going to be one function there.

**Comment by linki** [comment]
@fabioberger @albrow Thanks for comments. I'm away for a couple of days, will take a look next week.

**Comment by albrow** [comment]
@linki I know things are moving fast in this repo and I imagine that is making it more difficult for you to keep up. Do you still have time to update this PR and address all the merge conflicts? If not, we can take over from here (and you will still get credit for your commits up until this point).

**Comment by linki** [comment]
@albrow I'll try to merge it soon.

**Comment by linki** [comment]
@albrow rebased on master

**Comment by albrow** [comment]
Superseded by https://github.com/0xProject/0x-mesh/pull/184.

Thank you @linki for getting started on this and thank you for your patience.

Unfortunately, by the time we got the chance to take a look at your PR, there were already new merge conflicts. This PR touches a lot of code, so this is going to keep happening. I think the only way to get it merged is to temporarily halt work on other PRs, then fix any merge conflicts and merge this feature all in one go. It requires some pretty precise timing, which makes it difficult for @fabioberger and I to coordinate on this with an external contributor.

https://github.com/0xProject/0x-mesh/pull/184 starts with all the commits you already made here. I credited you on that PR explicitly, and when it is merged you should see your name show up in the contributor list for the repo as well. Thank you again 😄

**Comment by linki** [comment]
@albrow All good. Thanks for finishing it :smiley:

**Pull request closed without merging**
